### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by raccrompton** [landonepps/MorphMan21#63]
Hi, thanks for all your hard work! I updated the add on, and now receive this error when I open anything MM related:

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-12-10 14:07:49

Caught exception:
Traceback (most recent call last):
  File "C:\Users\raccr\AppData\Roaming\Anki2\addons21\900801631\morph\util_external.py", line 41, in __call__
    return self.cache[args]
KeyError: ()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\raccr\AppData\Roaming\Anki2\addons21\900801631\morph\mecab_wrapper.py", line 228, in mecab
    return spawnMecab(['mecab'], si), 'System'
  File "C:\Users\raccr\AppData\Roaming\Anki2\addons21\900801631\morph\mecab_wrapper.py", line 123, in spawnMecab
    config_dump = spawnCmd(base_cmd + ['-P'], startupinfo).stdout.read()
  File "C:\Users\raccr\AppData\Roaming\Anki2\addons21\900801631\morph\mecab_wrapper.py", line 120, in spawnCmd
    return subprocess.Popen(cmd, startupinfo=startupinfo, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1307, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\raccr\AppData\Roaming\Anki2\addons21\900801631\__init__.py", line 34, in onMorphManPreferences
    preferencesDialog.main()
  File "C:\Users\raccr\AppData\Roaming\Anki2\addons21\900801631\morph\preferencesDialog.py", line 393, in main
    mw.mm = PreferencesDialog(mw)
  File "C:\Users\raccr\AppData\Roaming\Anki2\addons21\900801631\morph\preferencesDialog.py", line 30, in __init__
    self.createNoteFilterTab()
  File "C:\Users\raccr\AppData\Roaming\Anki2\addons21\900801631\morph\preferencesDialog.py", line 62, in createNoteFilterTab
    self.setTableRow(i, row)
  File "C:\Users\raccr\AppData\Roaming\Anki2\addons21\900801631\morph\preferencesDialog.py", line 268, in setTableRow
    morphemizerComboBox.setMorphemizers(getAllMorphemizers())
  File "C:\Users\raccr\AppData\Roaming\Anki2\addons21\900801631\morph\UI\morphemizerComboBox.py", line 14, in setMorphemizers
    self.addItem(morphemizer.getDescription())
  File "C:\Users\raccr\AppData\Roaming\Anki2\addons21\900801631\morph\morphemizer.py", line 71, in getDescription
    return 'Japanese ' + getMecabIdentity()
  File "C:\Users\raccr\AppData\Roaming\Anki2\addons21\900801631\morph\mecab_wrapper.py", line 52, in getMecabIdentity
    m = mecab()
  File "C:\Users\raccr\AppData\Roaming\Anki2\addons21\900801631\morph\util_external.py", line 43, in __call__
    value = self.func(*args)
  File "C:\Users\raccr\AppData\Roaming\Anki2\addons21\900801631\morph\mecab_wrapper.py", line 230, in mecab
    raise OSError('''
OSError: 
            Mecab Japanese analyzer could not be found.
            Please install one of the following Anki add-ons:
                 https://ankiweb.net/shared/info/3918629684
                 https://ankiweb.net/shared/info/13462835
                 https://ankiweb.net/shared/info/278530045

**Comment by landonepps** [comment]
Do you have one of the above linked add-ons intalled?
MorphMan was originally designed to only work with Japanese and I believe we haven't yet made it optional.

**Comment by raccrompton** [comment]
you mean I should install one of these?

Please install one of the following Anki add-ons:
https://ankiweb.net/shared/info/3918629684
https://ankiweb.net/shared/info/13462835
https://ankiweb.net/shared/info/278530045


Huh interesting! I've been using MM for several months (for Dutch with the
spaced morphemizer) without any of those installed, and with no issues! I
can install one tho if that's all it takes.

**Comment by landonepps** [comment]
Try installing https://ankiweb.net/shared/info/3918629684 and see if that fixes it.

**Comment by raccrompton** [comment]
Yep that works! Thank you 👍

**Comment by landonepps** [comment]
It looks like the issue may have been fixed in the newest release. You can try removing Japanese Support after updating MorphMan. Just double-check that Japanese isn't selected in your MorphMan preferences.
